const SECONDS_PER_MONTH = 2628000;

const MONTHS_TO_CLIFF = 11;
const MONTHS_TO_RELEASE = 1;

const VESTED_TOKENS = 1200;

if (VESTED_TOKENS % MONTHS_TO_RELEASE !== 0 ) {
  throw new ReferenceError("Total vested token amount is not cleanly divisible by the months");
}

const TOKENS_PER_MONTH = VESTED_TOKENS / MONTHS_TO_RELEASE;

const CLIFF_DURATION = SECONDS_PER_MONTH * MONTHS_TO_CLIFF;
const RELEASABLE_DURATION = SECONDS_PER_MONTH * MONTHS_TO_RELEASE;
const TOTAL_VEST_DURATION = RELEASABLE_DURATION + CLIFF_DURATION;

if (RELEASABLE_DURATION % SECONDS_PER_MONTH !== 0) {
  throw new ReferenceError("Releasable duration is a multiple of months");
}

module.exports = {
  SECONDS_PER_MONTH,
  MONTHS_TO_CLIFF,
  MONTHS_TO_RELEASE,
  VESTED_TOKENS,
  TOKENS_PER_MONTH,
  CLIFF_DURATION,
  RELEASABLE_DURATION,
  TOTAL_VEST_DURATION
};
